'use strict'
angular.module('app.config', []).constant 'ENV',
  name: 'development'
  API_URL: 'https://api.topcoder-dev.com/v3'
  API_URL_V2: 'https://api.topcoder-dev.com/v2'
  clientId: 'JFDo7HMkf0q2CkVFHojy3zHWafziprhT'
  domain: 'topcoder-dev.com'
  auth0Domain: 'topcoder-dev.auth0.com'
  auth0Callback: 'no-callback-needed-without-social-login'
  submissionDownloadPath: '/review/actions/DownloadContestSubmission?uid='
  photoLinkLocation: 'http://community.topcoder.com'
